# -*- coding: utf-8 -*-
"""Post Test 2 ASD Searching (Praktikum 2023).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VXRhYFXd3DPqPPeiU0y82Ikevi6bZg8i
"""

def linear_search(var, find):
    data_length= len(var)
    value = False
    var1 = []

    for m in range(0, data_length):
        if type(var[m]) == list:
            for f in range(0, len(var[m])):
                if find == var[m][f]:
                    value = True
                    var1.append((m,f))
        else:
            if find == var[m]:
                value = True
                var1.append(m)

    if value == True:
        for s in var1:
            if type(s) == tuple:
                print(find, "di Index", s[0], "pada Kolom", s[1])
            else:
                print(find, "di Index", s)
    else:
        print("Data tidak ditemukan")
        
var = ["Arsel", "Avivah", "Daiva",["Wahyu", "Wibi"]]
print(var)

find = input("Ingin mencari data siapa? ").capitalize()
linear_search(var, find)